# Generated by Django 5.2.4 on 2025-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_type',
            field=models.CharField(choices=[('fc', 'Fixed Cost (FC) - Monthly cost that does not change with sales'), ('ivc', 'Indirect Variable Cost (IVC) - Changes with sales but not linked to specific sale'), ('dvc', 'Direct Variable Cost (DVC) - Only exists when sale happens and tied to that sale')], default='fc', help_text='Cost classification: FC, IVC, or DVC', max_length=10),
        ),
    ]
