# Generated by Django 5.2.4 on 2025-11-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_financialcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
    ]
