# Generated by Django 5.2.4 on 2025-11-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_financialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='person',
            field=models.ForeignKey(
                blank=True,
                help_text='Person/User associated with this expense',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='person_expenses',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(
                blank=True,
                help_text='Attachment file',
                null=True,
                upload_to='financial/expenses/attachments/'
            ),
        ),
    ]
