# Generated by Django 5.2.4 on 2025-11-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_add_person_and_attachment_to_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(
                choices=[
                    ('fixed', 'Fixed'),
                    ('variable', 'Variable'),
                    ('fc', 'Fixed Cost (FC)'),
                    ('ivc', 'Indirect Variable Cost (IVC)'),
                    ('dvc', 'Direct Variable Cost (DVC)'),
                ],
                default='fc',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(
                blank=True,
                help_text='Expense name/description (optional)',
                max_length=255,
                null=True
            ),
        ),
    ]
