# Generated by Django 5.2.4 on 2025-11-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_alter_expense_expense_type_alter_expense_name'),
    ]

    operations = [
        # Remove fields from Expense model
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_id_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_file',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='department',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='requires_approval',
        ),
        # Update currency default
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(
                choices=[
                    ('CLP', 'Chilean Peso'),
                    ('USD', 'US Dollar'),
                    ('EUR', 'Euro'),
                    ('BRL', 'Brazilian Real'),
                    ('ARS', 'Argentine Peso'),
                ],
                default='USD',
                max_length=3
            ),
        ),
    ]
