# Generated by Django 5.2.4 on 2025-11-25 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_remove_expense_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='financial_e_expense_44f2dd_idx',
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='financial_e_expense_70dd5b_idx'),
        ),
    ]
