# Generated by Django 5.2.4 on 2025-11-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_remove_expense_fields'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(
                blank=True,
                help_text='Bank account/payment method used to pay this expense',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='expenses',
                to='settings_app.paymentaccount'
            ),
        ),
    ]
