# Generated by Django 5.2.4 on 2025-11-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_expense_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='parent_expense',
            field=models.ForeignKey(blank=True, help_text='Parent expense for recurring expense entries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_children', to='financial.expense'),
        ),
    ]
