# Generated by Django 5.2.4 on 2025-11-25 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_remove_expense_financial_e_expense_44f2dd_idx_and_more'),
        ('settings_app', '0008_alter_systemappearance_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso')], help_text='Currency of the source account', max_length=3)),
                ('source_amount', models.DecimalField(decimal_places=2, help_text='Amount withdrawn from source account', max_digits=12)),
                ('destination_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso')], help_text='Currency of the destination account', max_length=3)),
                ('destination_amount', models.DecimalField(decimal_places=2, help_text='Amount deposited to destination account (after conversion)', max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate used (source to destination)', max_digits=12)),
                ('transfer_date', models.DateField(help_text='Date of the transfer')),
                ('description', models.TextField(blank=True, help_text='Description or note for the transfer', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference or transaction number', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', help_text='Transfer status', max_length=20)),
                ('receipt', models.FileField(blank=True, help_text='Attached receipt or proof of transfer', null=True, upload_to='financial/transfers/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(help_text='Bank account to which funds are transferred', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='settings_app.paymentaccount')),
                ('source_account', models.ForeignKey(help_text='Bank account from which funds are transferred', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='settings_app.paymentaccount')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['transfer_date'], name='financial_b_transfe_ec91fc_idx'), models.Index(fields=['source_account'], name='financial_b_source__b7bbdb_idx'), models.Index(fields=['destination_account'], name='financial_b_destina_5309ea_idx'), models.Index(fields=['status'], name='financial_b_status_c0bffb_idx')],
            },
        ),
    ]
