# Generated by Django 5.2.4 on 2025-09-01 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(max_length=50, unique=True)),
                ('operation_date', models.DateField()),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no-show', 'No Show')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial'), ('refunded', 'Refunded'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infant_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('salesperson', models.CharField(blank=True, max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('guide', models.CharField(blank=True, max_length=255)),
                ('driver', models.CharField(blank=True, max_length=255)),
                ('external_agency', models.CharField(blank=True, max_length=255)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tours.tour')),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-operation_date'],
            },
        ),
    ]
