# Generated by Django 5.2.4 on 2025-10-13 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_created_by'),
        ('reservations', '0001_initial'),
        ('settings_app', '0003_vehicle'),
        ('tours', '0003_rename_is_active_tour_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_source', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Website'), ('referral', 'Referral'), ('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='website', max_length=50)),
                ('currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real')], default='CLP', max_length=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('quotation_comments', models.TextField(blank=True)),
                ('send_quotation_access', models.BooleanField(default=True)),
                ('shareable_link', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.customer')),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('method', models.CharField(choices=[('credit-card', 'Credit Card'), ('debit-card', 'Debit Card'), ('bank-transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('copy_comments', models.BooleanField(default=True)),
                ('include_payment', models.BooleanField(default=True)),
                ('quote_comments', models.TextField(blank=True)),
                ('send_purchase_order', models.BooleanField(default=True)),
                ('send_quotation_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='reservations.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_payments',
            },
        ),
        migrations.CreateModel(
            name='BookingTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('pickup_time', models.CharField(blank=True, max_length=10)),
                ('adult_pax', models.IntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_pax', models.IntegerField(default=0)),
                ('child_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('infant_pax', models.IntegerField(default=0)),
                ('infant_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.CharField(choices=[('own-operation', 'Own Operation'), ('third-party', 'Third Party')], default='own-operation', max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tours', to='reservations.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_tours', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_tours', to='settings_app.destination')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_tours', to='tours.tour')),
            ],
            options={
                'db_table': 'booking_tours',
                'ordering': ['date'],
            },
        ),
    ]
