# Generated by Django 5.2.4 on 2025-09-06 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_address_customer_cpf_customer_language_and_more'),
        ('reservations', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('tour_type', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('passengers', models.IntegerField()),
                ('total_adults', models.IntegerField(default=0)),
                ('total_children', models.IntegerField(default=0)),
                ('total_infants', models.IntegerField(default=0)),
                ('hotel', models.CharField(blank=True, max_length=255)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('lead_source', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('website', 'Website'), ('referral', 'Referral'), ('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('additional_notes', models.TextField(blank=True)),
                ('has_multiple_addresses', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('quotation_comments', models.TextField(blank=True)),
                ('include_payment', models.BooleanField(default=True)),
                ('copy_comments', models.BooleanField(default=True)),
                ('send_purchase_order', models.BooleanField(default=True)),
                ('send_quotation_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('method', models.CharField(choices=[('credit-card', 'Credit Card'), ('debit-card', 'Debit Card'), ('bank-transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='reservations.booking')),
            ],
            options={
                'db_table': 'booking_payments',
            },
        ),
        migrations.CreateModel(
            name='BookingPricingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_breakdown', to='reservations.booking')),
            ],
            options={
                'db_table': 'booking_pricing_breakdown',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookingTour',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tour_reference_id', models.CharField(max_length=100)),
                ('tour_name', models.CharField(max_length=255)),
                ('tour_code', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_time', models.CharField(max_length=10)),
                ('adult_pax', models.IntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_pax', models.IntegerField(default=0)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infant_pax', models.IntegerField(default=0)),
                ('infant_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.CharField(choices=[('own-operation', 'Own Operation'), ('third-party', 'Third Party')], max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tours', to='reservations.booking')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_tours', to='tours.tour')),
            ],
            options={
                'db_table': 'booking_tours',
                'ordering': ['date'],
            },
        ),
    ]
