# Generated by Django 5.2.4 on 2025-10-25 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_customer_booking_bookingpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtour',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='cancellation_observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('trip-cancellation', 'Trip Cancellation [70% Retention]'), ('no-change-acceptance', 'Does not accept change suggestions [100% Retention]'), ('bad-weather', 'Bad weather [0% Retention]')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_booking_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkedin_booking_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='tour_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked-in', 'Checked In'), ('cancelled', 'Cancelled'), ('no-show', 'No Show'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
