# Generated by Django 5.2.4 on 2025-10-29 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_add_tour_status_and_cancellation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pax_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('-', 'Not Specified')], default='-', max_length=10)),
                ('nationality', models.CharField(blank=True, default='Not Informed', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.bookingtour')),
            ],
            options={
                'db_table': 'passengers',
                'ordering': ['booking_tour', 'pax_number'],
                'unique_together': {('booking_tour', 'pax_number')},
            },
        ),
    ]
