# Generated by Django 5.2.4 on 2025-09-09 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_add_user_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='copy_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='include_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='quote_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='send_purchase_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='send_quotation_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='reservations.booking'),
        ),
    ]
