# Generated by Django 5.2.4 on 2025-10-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
