# Generated by Django 5.2.4 on 2025-10-29 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_delete_reservation'),
        ('settings_app', '0003_vehicle'),
        ('tours', '0003_rename_is_active_tour_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['logistics_setting', 'booking_tour']},
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='LogisticsSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('operator', models.CharField(choices=[('own-operation', 'Own Operation'), ('others', 'Others')], default='own-operation', max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('assigned', 'Assigned'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_assistant_guide', to=settings.AUTH_USER_MODEL)),
                ('main_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_main_driver', to=settings.AUTH_USER_MODEL)),
                ('main_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_main_guide', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_settings', to='tours.tour')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_settings', to='settings_app.vehicle')),
            ],
            options={
                'db_table': 'logistics_settings',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='logistics_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.logisticssetting'),
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='pax_number',
        ),
    ]
