# Generated by Django 5.2.4 on 2025-10-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_passenger_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticssetting',
            name='operator',
        ),
    ]
