# Generated by Django 5.2.4 on 2025-10-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_logisticssetting_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='method',
            field=models.CharField(choices=[('pagarme-brl', 'Pagar.me (BRL)'), ('sicred-pix-brl', 'Sicred – Pix (BRL)'), ('cash-brl', 'Cash (BRL)'), ('cash-ars', 'Cash (ARS)'), ('cash-usd', 'Cash (USD)'), ('asaas-brl', 'Asaas (BRL)'), ('santander-ar', 'Santander (AR)'), ('wise-brl', 'Wise (BRL)'), ('wise-usd', 'Wise (USD)'), ('wise-eur', 'Wise (EUR)'), ('wise-clp', 'Wise (CLP)'), ('mercado-pago-ar', 'Mercado Pago (AR)')], max_length=50),
        ),
    ]
