# Generated by Django 5.2.4 on 2025-10-31 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_bookingpayment_method'),
        ('settings_app', '0003_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='assistant_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_as_assistant_guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='main_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_as_main_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='main_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_as_main_guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='operator_name',
            field=models.CharField(blank=True, help_text='Name of operator/supplier if third-party', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingtour',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tours', to='settings_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('reconfirmed', 'Reconfirmed'), ('no-show', 'No Show')], default='pending', max_length=20),
        ),
    ]
