# Generated by Django 5.2.4 on 2025-11-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_booking_is_locked_booking_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accept_term',
            field=models.BooleanField(default=False),
        ),
    ]
