# Generated by Django 5.2.4 on 2025-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_add_accept_term_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accept_term_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='accept_term_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='accept_term_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='accept_term_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
