# Generated by Django 5.2.4 on 2025-09-01 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('city', 'City Tour'), ('wine', 'Wine Tour'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('historical', 'Historical'), ('beach', 'Beach')], max_length=50)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infant_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('default_pickup_time', models.TimeField(blank=True, null=True)),
                ('min_participants', models.IntegerField(default=1)),
                ('max_participants', models.IntegerField(default=50)),
                ('operating_days', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['name'],
            },
        ),
    ]
