# Generated by Django 5.2.4 on 2025-09-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        ('tours', '0002_tour_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='max_participants',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='default_pickup_time',
            new_name='departure_time',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='inclusions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='infant_price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='min_participants',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='operating_days',
        ),
        migrations.AddField(
            model_name='tour',
            name='starting_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='settings_app.destination'),
        ),
    ]
