# Generated by Django 5.2.4 on 2025-11-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_baby_price_tour_cost_tour_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
