# Generated by Django 5.2.4 on 2025-11-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_change_operator_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
