# Generated by Django 5.2.4 on 2025-11-14 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_available_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='operator',
        ),
        migrations.AddField(
            model_name='tour',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operator_tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
