# Generated by Django 5.2.4 on 2025-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, help_text='Brazilian CPF if applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, help_text='ID Number or Document Number', max_length=100),
        ),
    ]
