# Generated by Django 5.2.4 on 2025-09-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_location_company_notes_avatar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='hotel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
