# Generated by Django 5.2.4 on 2025-10-22 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_alter_reservation_customer_booking_bookingpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, help_text='Total booking amount', max_digits=12)),
                ('costs', models.DecimalField(decimal_places=2, default=0, help_text='Total costs', max_digits=12)),
                ('net_received', models.DecimalField(decimal_places=2, help_text='Net amount after costs', max_digits=12)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount in booking currency', max_digits=12)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='reservations.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commissions', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
