# Generated by Django 5.2.4 on 2025-12-04 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('financial', '0012_add_bank_transfer_model'),
        ('reservations', '0012_add_recipe_fields_to_booking_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the commission was closed', null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='invoice_file',
            field=models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to='commissions/invoices/'),
        ),
        migrations.AddField(
            model_name='commission',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Generated invoice number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Whether this commission has been closed/finalized'),
        ),
        migrations.CreateModel(
            name='CommissionClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closing_type', models.CharField(choices=[('salesperson', 'Salesperson Commission'), ('agency', 'Agency Commission'), ('operator', 'Operator Payment')], max_length=20)),
                ('recipient_name', models.CharField(help_text='Name of salesperson, agency, or operator', max_length=255)),
                ('recipient_id', models.UUIDField(blank=True, help_text='User ID if salesperson', null=True)),
                ('period_start', models.DateField(help_text='Start of closing period')),
                ('period_end', models.DateField(help_text='End of closing period')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount closed', max_digits=14)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('item_count', models.IntegerField(default=0, help_text='Number of items closed')),
                ('invoice_number', models.CharField(help_text='Generated invoice number', max_length=50, unique=True)),
                ('invoice_file', models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to='closings/invoices/')),
                ('is_active', models.BooleanField(default=True, help_text='False if closing has been undone')),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('undo_reason', models.TextField(blank=True, help_text='Reason for undoing the closing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_closings', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_closings', to='financial.expense')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Closing',
                'verbose_name_plural': 'Commission Closings',
                'db_table': 'commission_closings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.commissionclosing'),
        ),
        migrations.CreateModel(
            name='OperatorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(help_text='Name of operator/supplier', max_length=255)),
                ('operation_type', models.CharField(choices=[('own-operation', 'Own Operation'), ('third-party', 'Third Party Operation')], default='third-party', max_length=20)),
                ('cost_amount', models.DecimalField(decimal_places=2, help_text='Amount to pay operator', max_digits=12)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('logistic_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reconfirmed', 'Reconfirmed'), ('completed', 'Completed'), ('no-show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Whether this payment has been closed/finalized')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the payment was closed', null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Generated invoice number', max_length=50, null=True)),
                ('invoice_file', models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to='operators/invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_payments', to='reservations.bookingtour')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_operator_payments', to=settings.AUTH_USER_MODEL)),
                ('closing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_payments', to='commissions.commissionclosing')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operator_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
