# Generated by Django 5.2.4 on 2025-12-04 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_add_closing_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('commission', 'Commission'), ('operator_payment', 'Operator Payment'), ('closing', 'Commission Closing')], max_length=30)),
                ('entity_id', models.UUIDField(help_text='ID of the changed commission, payment, or closing')),
                ('booking_id', models.UUIDField(blank=True, help_text='Related booking ID if applicable', null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('close', 'Closed'), ('reopen', 'Reopened'), ('adjust', 'Adjusted'), ('delete', 'Deleted')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Name of the changed field', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON-encoded if complex)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON-encoded if complex)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change (required for admin adjustments)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('closing', models.ForeignKey(blank=True, help_text='Closing this change was part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='commissions.commissionclosing')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Audit Log',
                'verbose_name_plural': 'Commission Audit Logs',
                'db_table': 'commission_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='commission__entity__119edf_idx'), models.Index(fields=['booking_id'], name='commission__booking_2ac716_idx'), models.Index(fields=['action'], name='commission__action_cdbbe1_idx'), models.Index(fields=['created_at'], name='commission__created_613854_idx'), models.Index(fields=['performed_by'], name='commission__perform_eb20fe_idx')],
            },
        ),
    ]
