# Generated by Django 5.2.4 on 2025-09-24 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('external_vehicle', models.BooleanField(default=False)),
                ('license_plate', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('vehicle_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
