# Generated by Django 5.2.4 on 2025-11-07 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('PEN', 'Peruvian Sol'), ('CLP', 'Chilean Peso'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_financial_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accountName', models.CharField(db_column='account_name', max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_payment_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('taxRate', models.DecimalField(db_column='tax_rate', decimal_places=2, default=0.0, max_digits=5)),
                ('bankSlipFee', models.DecimalField(db_column='bank_slip_fee', decimal_places=2, default=0.0, max_digits=5)),
                ('cashFee', models.DecimalField(db_column='cash_fee', decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_payment_fee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_and_conditions', models.TextField(blank=True, default='')),
                ('terms_file_url', models.CharField(blank=True, default='', max_length=500)),
                ('terms_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_terms_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
