# Generated by Django 5.2.4 on 2025-11-07 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_financialconfig_paymentaccount_paymentfee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso')], max_length=3)),
                ('to_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_exchange_rate',
                'ordering': ['-updated_at'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
