# Generated by Django 5.2.4 on 2025-11-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_systemappearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemappearance',
            name='logo_url',
        ),
    ]
