# Generated by Django 5.2.4 on 2025-11-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_remove_systemappearance_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemappearance',
            name='company_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
